spring.application.name=music-project

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

firebase.key.path=${FIREBASE_KEY_PATH}

spring.main.allow-circular-references=true

logging.level.com.example.student_system.musicproject=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO